# Generated by Django 4.0.5 on 2022-06-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filedata',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('child_part_no', models.IntegerField()),
                ('child_part_description', models.TextField()),
                ('item_ref_number', models.TextField()),
                ('quantity_production', models.FloatField()),
                ('created_on', models.DateField()),
            ],
        ),
    ]
