# Generated by Django 4.0.5 on 2022-06-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='child_part_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='quantity_production',
            field=models.CharField(max_length=255),
        ),
    ]
